### ISSUE TITLE
Server lags.

### ISSUE THREAD

**Issue by Chenterito** [diamante0018/DisablePlutoChat#44]
Since I started using it, the server is sometimes laggy. Instead when I don't use it, this doesn't happen. Yesterday I was using it again, hoping this wouldn't happen, but it did happen again. The server is laggy at times.

**Comment by diamante0018** [comment]
I made a new release of this plugin, you might want to try it out.

**Comment by diamante0018** [comment]
I moved the saving of the muted file code to an asynchronous thread, otherwise, I checked my plugin, and there is nothing that can cause lag.
Every single time a player types in the chat, the code needs to check that they are not muted.
The check is virtually a non-expensive operation because it is just checking for the player GUID is present in the database loaded in the memory or not.
If you think such a simple operation can cause lag, you should consider upgrading your CPU.
Thanks.
